title: "Cufarul lui Christianne"
description: "Bratari handmade"
url: "https://cufarul-lui-christianne.ro"
include: ["_headers", "_redirects"]
exclude: ["_drafts", ".jekyll-cache", "Gemfile.lock"]
permalink: /:title/
